<?php

use Illuminate\Database\Seeder;

class MaterialsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('materials')->insert([
        /*[
            'name' => '枝豆',
            'material_category_id' => '1',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'みそ',
            'material_category_id' => '1',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ], 
        [
            'name' => '調製豆乳',
            'material_category_id' => '1',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '無調製豆乳',
            'material_category_id' => '1',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ごま',
            'material_category_id' => '1',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '小豆',
            'material_category_id' => '1',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '煮小豆',
            'material_category_id' => '1',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
            [
            'name' => '豆腐',
            'material_category_id' => '1',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '黒豆',
            'material_category_id' => '1',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '米',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '強力粉',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '薄力粉',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'てんぷら粉',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '米(無洗米)',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '雑穀',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'コーン',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'パン粉',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'さつま芋',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '米粉',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '春巻きの皮',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'スパゲッティ',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'じゃがいも',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'フランスパン',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ラザニア',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'コーン（クリーム）',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'コーン(粒)',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '餃子の皮',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '中華麺(生・太麺)',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '角もち',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '冷凍パイシート',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'わらびもち粉',
            'material_category_id' => '2',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '白ねぎ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '水菜',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'きゅうり',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '玉ねぎ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '紫玉ねぎ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'セロリ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '赤パプリカ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'グリーンリーフ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '小松菜',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ほうれん草',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'トマト',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ゴーヤ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ズッキーニ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '大根',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '青じそ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '紅芯大根',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'わけぎ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ルッコラ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'プチトマト',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '人参',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'キムチ(白菜)',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'トレビス',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '青ねぎ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'キャベツ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ごぼう',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '春菊',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'たくわん',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'かぶ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '紫キャベツ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'かぼちゃ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'れんこん',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ピーマン',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '菜の花',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'スナップえんどう',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ニラ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'なす',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'オクラ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'みょうが',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '黄パプリカ',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'みつ葉',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ブ��ッコリー',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'しし唐辛子',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '長芋',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'グリーンアスパラガス',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '筍(水煮)',
            'material_category_id' => '3',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ライム',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ぶどう',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'りんご',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'レモン',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'エルダーフラワーコーディアル',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ミントの葉',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'セルフィーユ',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'バジル',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'アボガド',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'キウイフルーツ',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
            [
            'name' => 'バナナ',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'いちご',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '栗渋皮煮',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'グリーンレーズン',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ローリエ',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'オレンジ',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ブラックオリーブ',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'タイム',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ディル',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ラズベリー(冷凍)',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ブルーベリー(冷凍)',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'アーモンドスライス',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'サフラン',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'くるみ',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'マンゴー(冷凍)',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ライチ(缶)',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '生姜',
            'material_category_id' => '4',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'しめじ',
            'material_category_id' => '5',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'きざみ海苔',
            'material_category_id' => '5',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '焼き海苔',
            'material_category_id' => '5',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '椎茸',
            'material_category_id' => '5',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ポルチーニ茸',
            'material_category_id' => '5',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'わかめ',
            'material_category_id' => '5',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'まいたけ',
            'material_category_id' => '5',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'えのき茸',
            'material_category_id' => '5',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'マッシュルーム',
            'material_category_id' => '5',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ツナ缶',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '辛子明太子',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'アジ',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'むき海老',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'カニ風味かまぼこ',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'はんぺん',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'スモークサーモン',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'さきいか',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'あさり',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'あさり(殻付き)',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '海老(殻付き)',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'たらこ',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ちりめんじゃこ',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'かまぼこ',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '海老(有頭)',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ロブスター',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '鯛',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '鰤',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ほたて貝柱',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '練りうに',
            'material_category_id' => '6',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '牛肩ロース薄切り肉',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '鶏もも肉',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '豚ロース薄切り',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '豚バラ薄切り肉',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '鶏手羽中',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '鶏ひき肉',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ロースハム',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ベーコン',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '合い挽き肉',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '豚肩ロース塊肉',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '豚ひき肉',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'フォアグラ',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '豚肩ロース薄切り肉',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ウインナー',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '牛ステーキ肉',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '鶏手羽元',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '牛もも塊肉',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'スペアリブ',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '豚バラ塊肉',
            'material_category_id' => '7',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'インスタントコーヒー',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'グレープフルーツジュース',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ラム酒',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'クコの実',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '味つきザーサイ',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '黒練ごま',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'トマトジュース',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ピーナッツクリーム',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ピンクペッパー',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'レッドペッパー',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '赤ワイン',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ゆず茶',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'インスタントドライイースト',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ターメリック',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'クミンシード',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'クミンパウダー',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
       [
            'name' => 'ガラムマサラ',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '抹茶',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ストロベリーリキュール',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'サイダー',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '白ワイン',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'フランボワーズリキュール',
            'material_category_id' => '8',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'フロストシュガー',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '白玉粉',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'はちみつ',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'カステラ',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'フルーツグラノーラ',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'コーンフレーク',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'チョコレートシロップ',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '羊羹',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ココアパウダー',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'パイナップル(缶)',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '黒こしあん',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'マンゴージャム',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '粉糖',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'いちご(フリーズドライパウダー)',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'いちごジャム',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ブルーベリージャム',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '市販のマカロンミックス',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'きび砂糖',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '砂糖',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ミックスフルーツ(缶)',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'メープルシロップ',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '洋梨(缶)',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '市販のキャラメルシロップ',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ラズベリージャム',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'りんごジャム',
            'material_category_id' => '9',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '切り干し大根',
            'material_category_id' => '10',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ゆかり',
            'material_category_id' => '10',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '桜の花の塩漬け',
            'material_category_id' => '10',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '削りがつお',
            'material_category_id' => '10',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '素干し海老',
            'material_category_id' => '10',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '芽ひじき',
            'material_category_id' => '10',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'チリインオイル',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ナンプラー',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'スイートチリソース',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'マヨネーズ',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '市販のカットトマト',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'カレー粉',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '鶏がらスープの素',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'マスタード',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ウスターソース',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'バニラオイル',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ごま油',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'だしじょうゆ',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '片栗粉',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'オリーブオイル',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '和風だしの素',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ポン酢しょうゆ',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '黒こしょう',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'コンソメ顆粒',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '岩塩',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '市販のデミグラスソース',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '市販ホワイトソース',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '市販トマトソース',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'アーモンドパウダー',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'アーモンドエッセンス',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'カスタードクリームパウダー',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ココナッツミルクパウダー',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ベーキングパウダー',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'トマトケチャップ',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'トマトペースト',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'コチュジャン',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'チリパウダー',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '黒酢',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '白だし',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '白こしょう',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '赤唐辛子(輪切り)',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '粒マスタード',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ナツメグ',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '豆板醤',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'トウチ',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '青花椒(アオホワジャオ)',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'テンメジャン',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ラー油',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ターメリック',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'オイスターソース',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '酒',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '塩こうじ',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'しょうゆこうじ',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ゆずこしょう',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '市販のタルタルソース',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ハーブ&スパイスミックス調味料',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'チョウテンガンシンジャオ',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'にんにく',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'イタリアンパセリ',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'パセリ',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'バジル',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '生クリーム',
            'material_category_id' => '12',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'スライスチーズ',
            'material_category_id' => '12',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'バター',
            'material_category_id' => '12',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'バター(食塩不使用)',
            'material_category_id' => '12',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '牛乳',
            'material_category_id' => '12',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'サワークリーム',
            'material_category_id' => '12',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
                [
            'name' => 'ピザ用チーズ',
            'material_category_id' => '12',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '粉チーズ',
            'material_category_id' => '12',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'ラクレットチーズ',
            'material_category_id' => '12',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'クリームチーズ',
            'material_category_id' => '12',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'カマンベールチーズ',
            'material_category_id' => '12',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'プレーンヨーグルト',
            'material_category_id' => '12',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'プロセスチーズ',
            'material_category_id' => '12',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'コンデンスミルク',
            'material_category_id' => '12',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '温泉卵',
            'material_category_id' => '13',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '卵',
            'material_category_id' => '13',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '粉ゼラチン',
            'material_category_id' => '13',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],*/
        [
            'name' => '酢',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '塩',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '醤油',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'エキストラバージンオリーブオイル',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '削りがつお',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'たくわん',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '市販のドレッシング',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '市販のきざみしょうが',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '市販のきざみにんにく',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '市販のおろしにんにく',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '市販のおろししょうが',
            'material_category_id' => '11',
            'memo' => '', 
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],

    ]);
    }
}
