<?php

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('menus')->insert([
        [
            'name' => '2010A',
            'body' => '黒酢酢豚・きゅうりの浅漬け・中華風コーンスープ・黒ごまプリン',
            'image_path' => '0.10A.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2010B',
            'body' => 'チキンカレー・ほうれん草とヨーグルトのカレー・チーズクルチャ&ターメリックライス・マンゴーラッシー',
            'image_path' => '0.10B.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
         [
            'name' => '2010C',
            'body' => '手打ちニョッキのチーズグラタン・スパイシーチキン・かぼちゃとナッツのサラダ&トマトとルッコラのサラダ・まるごとマロンケーキ',
            'image_path' => '0.10C.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2011A',
            'body' => 'みそしょうが焼き・雑穀ご飯・ミネラルサラダ・きのこの豆乳みそ汁・キャラメル豆乳プリン',
            'image_path' => '0.11A.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2011B',
            'body' => 'チリトマトカルボナーラ・マスタードチキングリル・焼ききのこサラダ・洋梨のクラフティ',
            'image_path' => '0.11B.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2012A',
            'body' => 'ローストビーフ〜玉ねぎとしょうゆこうじのソース・トマトのポトフ〜チーズバゲット〜・グラスディップサラダ・ホワイトムース〜ベリーソース仕立て〜',
            'image_path' => '0.12A.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
         [
            'name' => '2012B',
            'body' => '伊達巻き寿司・スペアリブの香味みそ焼き・海老のタルタルグリル・紅芯大根のゆずこしょう甘酢・かまぼこのクリームチーズサンド・関東風雑煮',
            'image_path' => '0.12B.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2012C',
            'body' => 'ロブスターのビスク風パスタ・マッシュルームと温泉卵のサラダ・ヴィシソワーズ・ショコラケイク',
            'image_path' => '0.12C.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2101A',
            'body' => '牛肉のステーキ〜レモンバター醤油仕立て〜・クラムチャウダー・グリーンサラダ・バラのクレープ',
            'image_path' => '1.01A.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2101B',
            'body' => '万能だれ・鰤の竜田揚げ&長芋わかめ天・雑穀ご飯・圧力調理バッグで時短チャーシュー・ザーサイとかぶの豆乳みそ汁・アップルサイダーゼリー',
            'image_path' => '1.01B.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2101C',
            'body' => '真鯛のポワレ〜サルサヴェルデ仕立て〜・ホタテのサフランリゾット・トマトドレッシングのサラダ・塩キャラメルミルフィーユ',
            'image_path' => '1.01C.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2102A',
            'body' => 'ボロネーゼソースのラザニア・オニオングラタンスープ・スモークサーモンのサラダ・チョコバナナパフェ',
            'image_path' => '1.02A.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2102B',
            'body' => '5種ナムルのビビンパ・卵と海苔のスープ・チーズタッカルビ・ゆず茶のケーキ',
            'image_path' => '1.02B.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2102C',
            'body' => 'フォグラハンバーグステーキ・キャロットポタージュ・グリーンサラダ・珈琲プリン',
            'image_path' => '1.02C.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2103A',
            'body' => 'チキン南蛮〜たくあんタルタル添え・雑穀ご飯・キャベツのかきたまみそ汁・あさりと春野菜の酒蒸し・抹茶豆乳ババロア',
            'image_path' => '1.03A.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2103B',
            'body' => '桜ごはん・レンジで作る洋風つくね・海老と青じその春巻き・和風ジャーマンポテト・切り干し大根のゆかり甘酢・卵焼き・桜餅',
            'image_path' => '1.03B.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2103C',
            'body' => 'うにトマトクリーム仕立てのロールキャベツ・菜の花とアボガドのエッグサラダ・カマンベールチーズのパーネ・オレンジのパンナコッタ',
            'image_path' => '1.03C.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2104A',
            'body' => '・ハッシュドビーフのオムライス・コブサラダ・いちごのスノーボールクッキー',
            'image_path' => '1.04A.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2104B',
            'body' => '四川風麻婆豆腐・雲白肉〜ウンパイロー〜・黄金チャーハン・杏仁プリン',
            'image_path' => '1.04B.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2104C',
            'body' => '肉バルのラクレットプレート〜豚肉のハニーロースト&ミートボール・あさりとレモンのパエリア・オニオンサラダ・ストロベリースパークリング',
            'image_path' => '1.04C.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2105A',
            'body' => '十勝若牛のステーキディッシュ・ガーリックライス・パイナップルとキャベツのコールスロー・飲むチーズケーキ',
            'image_path' => '1.05A.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2105B',
            'body' => '2種のパスタ〜アマトリチャーナ&冷製たらこレモン・バジルチキンサラダ・キウイヨーグルト',
            'image_path' => '1.05B.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2105C',
            'body' => '韓国風ザクザクチキン&ヤンニョムチキン・チーズキンパ・わかめの炒めドレッシングサラダ・トゥンカロン〜韓国風マカロン〜',
            'image_path' => '1.05C.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2106A',
            'body' => '台湾まぜそば・ぷりぷり海老餃子・白いたまごプリン',
            'image_path' => '1.06A.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2106B',
            'body' => '5種野菜と鶏肉のごま香味炒め・オクラとみょうがの冷たいみそ汁・桜海老とチーズの卵焼き・小松菜のごま和え・フルーツ和ポンチ',
            'image_path' => '1.06B.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2106C',
            'body' => '豚しゃぶのスープカレー・ターメリックライス・グリルチキンウイング・アボガドとトマトのサラダ・ココナッツミルクラッシー',
            'image_path' => '1.06C.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2107A',
            'body' => 'スコッチエッグ・アスパラフライ・炒り黒豆のごはん・揚げなすのみそ汁・抹茶くるみわらび餅',
            'image_path' => '1.07A.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2107B',
            'body' => 'ガパオライス・チャーゾー〜ベトナム風揚げ春巻き〜・牛肉とミントのサラダ・マンゴーミルク',
            'image_path' => '1.07B.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2107C',
            'body' => '焼き小籠包・ラーズーチー〜鶏のから揚げ甘辛四川炒め〜トマトと卵のスープ・ライチプリン',
            'image_path' => '1.07C.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2108A',
            'body' => 'すき焼き丼・枝豆とたたききゅうりのサラダ・焼き枝豆のみそ汁・甘酒クリームコーヒーゼリー',
            'image_path' => '1.08A.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2108B',
            'body' => 'プーパッポンカリー〜ソフトシェルクラブと卵のカレー炒め〜・鶏肉のピーナッツグリル・エスニックツナサラダ・グレープフルーツゼリー',
            'image_path' => '1.08B.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2108C',
            'body' => '手打ちうどん〜明太チーズかま玉&トマトだしつゆ〜・豚竜田揚げのサラダ仕立て・みたらし団子',
            'image_path' => '1.08C.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2109A',
            'body' => '鯵フライ・雑穀ご飯・手羽中と大根のスピード煮物・大根みそ汁・季節の水菓子',
            'image_path' => '1.09A.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2109B',
            'body' => '海老コーン天むす・カラフルチキンボール・ふわふわハムたまチーズ・ズッキーニの焼きナムル・きのこのレモンソテー・紅芯大根の甘酢漬け・ブルーベリー大福',
            'image_path' => '1.09B.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2109C',
            'body' => 'フレッシュポルチーニのクリームパスタ・鶏肉のトマト煮込み・ぶどうとレモンのサラダ・さつま芋のモンブラン',
            'image_path' => '1.09C.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2110A',
            'body' => 'サクサクとろーり五目おこげ・海老チリ春巻き・わかめとザーサイの和え物・レモンティーゼリー',
            'image_path' => '1.10A.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2110B',
            'body' => 'デミグラス煮込みチーズハンバーグ・かぼちゃのみそ汁・りんごと春菊のサラダ・カスタードアップルパイ',
            'image_path' => '1.10B.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => '2110C',
            'body' => 'チキンとかぼちゃのガーリッククリームシチュー〜シュクメルリ・とろーり卵のチーズブレッド〜ハチャプリ・ハロウィンサラダ・ウフアラネージュ〜メレンゲデザート',
            'image_path' => '1.10C.jpg',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'kids',
            'body' => '基本のポークソテー',
            'image_path' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'kids',
            'body' => 'レンジで！もやしと豆苗の豚巻きレンジ蒸し',
            'image_path' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'kids',
            'body' => '香りもごちそう鮭のガリバタ醤油ムニエル',
            'image_path' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'kids',
            'body' => 'やみつきピリ辛きゅうり',
            'image_path' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'kids',
            'body' => 'ジューシー鶏の唐揚げ',
            'image_path' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'kids',
            'body' => 'ふんわりやわらか！簡単海老チリ',
            'image_path' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'hiro',
            'body' => '牡蠣とほうれん草のレモンクリームパスタ',
            'image_path' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'hiro',
            'body' => 'しじみの中華スープ',
            'image_path' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'hiro',
            'body' => 'はまぐりの潮汁',
            'image_path' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'hiro',
            'body' => 'アアスパラと海老の塩ソース蒸し',
            'image_path' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'hiro',
            'body' => 'あおさ汁',
            'image_path' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'hiro',
            'body' => '茶碗蒸し',
            'image_path' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'hiro',
            'body' => 'アジのたたき',
            'image_path' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'hiro',
            'body' => 'カレーパン',
            'image_path' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
        [
            'name' => 'hiro',
            'body' => '鶏肉のトマト煮込み(カチャトーラ)',
            'image_path' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
         ],
         

    ]);     
    }
}