<?php

use Illuminate\Database\Seeder;

class NutrientMaterialsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('nutrient_materials')->insert([
        [
            'nutrient_id' => '1',
            'material_id' => '5',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '1',
            'material_id' => '6',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '1',
            'material_id' => '103',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '1',
            'material_id' => '257',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '1',
            'material_id' => '258',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '1',
            'material_id' => '89',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '1',
            'material_id' => '94',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '1',
            'material_id' => '98',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '1',
            'material_id' => '99',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '1',
            'material_id' => '100',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '2',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '3',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '4',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '5',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '6',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '8',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '9',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '16',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '18',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '22',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '32',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '33',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '34',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '37',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '38',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '70',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '256',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '40',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '41',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '42',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '43',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '44',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '45',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '46',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '48',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '49',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '51',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '52',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '53',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '103',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '54',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '55',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '56',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '57',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '59',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '60',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '61',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '62',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '63',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '64',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '65',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '66',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '67',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '68',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '69',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '71',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '72',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '73',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '74',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '75',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '76',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '199',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '233',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '241',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '250',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '256',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '77',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '78',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '79',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '257',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '258',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '259',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '85',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '86',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '87',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '88',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '90',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '89',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '92',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '94',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '197',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '98',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '100',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '101',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '102',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '107',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '108',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '110',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '111',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '112',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '2',
            'material_id' => '109',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '3',
            'material_id' => '259',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '3',
            'material_id' => '258',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '3',
            'material_id' => '38',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '3',
            'material_id' => '70',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '4',
            'material_id' => '275',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '4',
            'material_id' => '274',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '4',
            'material_id' => '203',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '4',
            'material_id' => '90',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '4',
            'material_id' => '94',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '4',
            'material_id' => '118',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '4',
            'material_id' => '117',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '4',
            'material_id' => '120',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '4',
            'material_id' => '121',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '4',
            'material_id' => '126',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '4',
            'material_id' => '128',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '4',
            'material_id' => '131',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '4',
            'material_id' => '132',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '5',
            'material_id' => '204',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '5',
            'material_id' => '250',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '5',
            'material_id' => '109',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '5',
            'material_id' => '106',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '1',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '18',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '22',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '32',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '34',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '33',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '35',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '37',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '38',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '70',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '40',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '43',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '44',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '45',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '46',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '48',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '49',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '51',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '52',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '54',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '55',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '57',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '59',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '60',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '61',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '62',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '63',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '65',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '72',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '73',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '75',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '199',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '256',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '77',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '80',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '85',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '86',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '87',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '88',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '92',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '101',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '102',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '158',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '6',
            'material_id' => '183',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '18',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '33',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '34',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '38',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '70',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '40',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '41',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '42',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '44',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '45',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '46',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '49',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '51',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '54',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '57',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '59',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '63',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '64',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '65',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '66',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '68',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '71',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '72',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '73',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '75',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '135',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '275',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '274',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '261',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '263',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '262',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '264',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '266',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '267',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '268',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '269',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '278',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '272',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '271',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '273',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '204',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '233',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '242',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '257',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '258',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '259',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '109',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '106',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '134',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '137',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '136',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '135',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '139',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '140',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '141',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '133',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '142',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '143',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '144',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '145',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '146',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '147',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '148',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '150',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '151',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '7',
            'material_id' => '158',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '15',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '256',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '250',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '133',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '134',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '135',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '138',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '137',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '136',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],      
        [
            'nutrient_id' => '8',
            'material_id' => '139',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '140',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '141',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '142',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '143',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '144',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '145',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '146',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '147',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '148',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '149',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '150',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '8',
            'material_id' => '151',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '274',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '275',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '261',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '264',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '266',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '267',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '268',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '269',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '278',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '272',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '271',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '273',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '203',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '250',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '104',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '107',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '108',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '110',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '111',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '112',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '116',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '117',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '118',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '120',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '121',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '126',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '128',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '131',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '9',
            'material_id' => '132',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '10',
            'material_id' => '3',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '10',
            'material_id' => '4',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '10',
            'material_id' => '9',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '10',
            'material_id' => '15',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '10',
            'material_id' => '16',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '10',
            'material_id' => '256',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '10',
            'material_id' => '103',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '10',
            'material_id' => '64',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '10',
            'material_id' => '241',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '10',
            'material_id' => '259',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '10',
            'material_id' => '257',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '10',
            'material_id' => '258',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '10',
            'material_id' => '106',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '6',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '8',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '32',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '33',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '256',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '40',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '41',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '45',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '46',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '49',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '103',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '54',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '56',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '57',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '59',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '60',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '64',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '66',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '68',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '261',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '264',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '265',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '266',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '268',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '267',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '269',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '270',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '272',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '271',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '273',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '199',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '202',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '203',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '204',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '250',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '257',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '258',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '259',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '94',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '98',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '99',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '109',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '113',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '114',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '115',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '116',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '117',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '118',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '119',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '120',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '121',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '124',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '125',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '126',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '128',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '130',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '129',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '131',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '11',
            'material_id' => '132',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '12',
            'material_id' => '202',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '12',
            'material_id' => '250',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '12',
            'material_id' => '104',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '12',
            'material_id' => '107',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '12',
            'material_id' => '108',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '12',
            'material_id' => '110',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '12',
            'material_id' => '111',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '12',
            'material_id' => '112',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '12',
            'material_id' => '113',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '12',
            'material_id' => '114',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '12',
            'material_id' => '115',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '12',
            'material_id' => '119',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '12',
            'material_id' => '124',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '12',
            'material_id' => '125',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '12',
            'material_id' => '130',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '12',
            'material_id' => '129',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '13',
            'material_id' => '262',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '13',
            'material_id' => '263',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '13',
            'material_id' => '202',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '13',
            'material_id' => '93',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '13',
            'material_id' => '94',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '13',
            'material_id' => '98',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '13',
            'material_id' => '113',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '13',
            'material_id' => '114',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '13',
            'material_id' => '115',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '13',
            'material_id' => '119',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '13',
            'material_id' => '99',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '13',
            'material_id' => '124',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '13',
            'material_id' => '125',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '13',
            'material_id' => '130',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '13',
            'material_id' => '129',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '14',
            'material_id' => '2',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '14',
            'material_id' => '52',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '14',
            'material_id' => '103',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '14',
            'material_id' => '261',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '14',
            'material_id' => '262',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '14',
            'material_id' => '266',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '14',
            'material_id' => '267',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '14',
            'material_id' => '268',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '14',
            'material_id' => '269',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '14',
            'material_id' => '272',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '14',
            'material_id' => '206',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '14',
            'material_id' => '242',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '14',
            'material_id' => '257',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '14',
            'material_id' => '258',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '14',
            'material_id' => '106',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '14',
            'material_id' => '114',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '15',
            'material_id' => '3',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '15',
            'material_id' => '4',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '15',
            'material_id' => '43',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '15',
            'material_id' => '64',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '15',
            'material_id' => '204',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '15',
            'material_id' => '250',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '15',
            'material_id' => '258',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '15',
            'material_id' => '257',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '15',
            'material_id' => '259',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '15',
            'material_id' => '108',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '6',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '8',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '274',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '275',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '276',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '260',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '261',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '262',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '263',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '264',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '265',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '266',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '267',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '268',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '269',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '270',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '272',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '271',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '273',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '202',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '203',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '113',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '115',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '116',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '117',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '118',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '119',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '120',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '121',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '124',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '125',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '126',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '130',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '128',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '129',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '131',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '16',
            'material_id' => '132',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '6',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '18',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '22',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '137',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '32',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '40',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '56',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '61',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '64',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '66',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '68',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '72',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '73',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '74',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '76',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '199',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '80',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '85',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '90',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '111',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '17',
            'material_id' => '109',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '18',
            'material_id' => '6',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '18',
            'material_id' => '9',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '18',
            'material_id' => '250',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],
        [
            'nutrient_id' => '19',
            'material_id' => '79',
            'memo' => '',
            'created_at' => new DateTime(),
            'updated_at' => new DateTime(),
        ],

    ]);        
    }
}
